<?php
  session_start();
  
  ini_set('display_errors','On');
  error_reporting(E_ALL);

  $title = 'Fundasol';

?>
<!DOCTYPE html>
<html>
<head>
  <link href='css/bootstrap.css' rel='stylesheet'>
  <link href='css/custom.css' rel='stylesheet'>
  <link href='css/jquery-ui-1.9.2.custom.css' rel='stylesheet'>
  <link href='css/bootstrap-spinedit.css' rel='stylesheet'>

</head>
<body>

  <!-- Linking JS files -->
  <script src='js/jquery-1.9.1.js'></script>
  <script src='js/bootstrap.js'></script>
  <script src='js/ajaxHandler.js'></script>
  <script src='js/jquery-ui-1.10.3.custom.min.js'></script>
  <script src='js/jquery.maskMoney.js'></script>
  <script src='js/bootstrap-spinedit.js'></script>
  <!-- <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script> -->

  <!-- Nav Bar -->
  <div class='navbar navbar-static-top'>
    <div class='navbar-inner'>
      <a class='brand' href='#'><?php echo $title ?></a>
      <ul class='nav'>
        <li class='dropdown'>
          <a href='#' class='dropdown-toggle' data-toggle='dropdown'>Clientes</a>
          <ul class='dropdown-menu'>
            <li><a href='#' id='showClientsBtn'>Mostrar</a></li>
            <li><a href='#' id='createClientBtn'>Crear Nuevo</a></li>
          </ul>
        </li>
        <li class='dropdown'>
          <a href="#" class='dropdown-toggle' data-toggle='dropdown'>Cuentas</a>
          <ul class='dropdown-menu'>
            <li><a href="#" id='showAccountsBtn'>Mostrar</a></li>
          </ul>
        </li>
        <li><a href="#">Reportes</a></li>
      </ul>
      <!-- Search Bar Section -->
      <form class="navbar-search form-search pull-right" method="POST">
        <!-- search bar box with buttons -->
        <div class="input-append">
          <input type="text" class="search-query" list="accountsAndClients" placeholder="Apellido, Nombre" name="search" value="search" >
          <button type="submit" class="btn btn-custom"> 
            <i class="icon-search"> </i> 
          </button>
          <button type="submit" class="btn"> 
            <i class="icon-barcode"></i> 
          </button>
        </div>
        <!-- Data list that populates on the search bar -->
        <datalist id="accountsAndClients"> 
          <?php
            // populateDatalist();
          ?>
        </datalist>
      </form>
    </div>
  </div>
  <div class="container">        
    <!-- Client Info or Receipts Section -->
    <div class="row">
      <div class="span12">    
       <div id='viewContent'></div>
      </div>
    </div>
  </div>
  
</body>
</html>
