<form method='POST' action='modules/actions/account.create.php'>
  <div class='control-group'>
    <div class='controls'>
      <input type='text' placeholder='Cantidad' name='amount' required>
    </div>
  </div>
  <div class='control-group'>
    <div class='controls'>
      <input type='text' placeholder='Semanas' name='n_payments' required>
    </div>
  </div>
  <div class='control-group'>
    <div class='controls'>
      <input type='date' placeholder='1ra Semana' name='start_week' required> 
    </div>
  </div>
  <div class='form-actions'>
    <button type='submit' class='btn btn-primary'> Crear cuenta </button>
    <button type='button' class='btn' id='account_cancel_btn'> Cancelar </button>
  </div> 
</form>