<form class='form-horizontal' action='modules/actions/client.create.php' method='POST'> 
  <legend> Nuevo Cliente </legend>
  <div class='control-group'>
    <div class='controls'>
      <input type='text' name='first_name' placeholder='Nombre'>
    </div> 
  </div>
  <div class='control-group'>
    <div class='controls'>
      <input type='text' name='last_name' placeholder='Apellido'>
    </div> 
  </div>
  <div class='control-group'>  
    <div class='controls'>
      <input type='text' name='state_id' placeholder='Cedula de Identidad'>
    </div>
  </div>
  <div class='control-group'>
    <div class='controls'>
      <input type='submit' value='Crear Cliente' class='btn'>
    </div>
  </div>
</form>