<?php
session_start();
?>
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <?php
      $title = "Create a new receipt";  
    ?>
    <h1> <? echo $title ?> </h1>
    <?php
    $msg = "Before anything";
    if (isset($_SESSION['receipt_create_msg'])) {
      $msg = $_SESSION['receipt_create_msg'];
    }
    ?>
    <h3> <?php echo $msg ?> </h3>
    <form action="modules/actions/receipt.create.php" method="post" class="form-inline"> 
      <input type="hidden" class="hidden" name="receipt_create_msg">
      <input type="text" id="receipt_amount" name="amount" placeholder="Cantidad" required>
      <input type="submit" value="Pagar" class="btn">
    </form>
  </body>
</html>