<?php
  //session_start();
  $title = "Pago";  
?>
<div class="well">
  <?php
  $msg = "Before anything";
  $search_result = $_SESSION['search_result'];
  if (isset($_SESSION['receipt_create_msg'])) {
    $msg = $_SESSION['receipt_create_msg'];
  }
  ?>
  <?php
    $conn = mysqli_connect("localhost", "root", "root", "fundasol");
    $sql_client = "Select * from Clients where Clients.id = " . $search_result;
    $sql_account = "Select * from Accounts where Accounts.client_id=" . $search_result;
    $sql_receipts = "Select * from Receipts where Receipts.account_id IN (SELECT id FROM Accounts WHERE Accounts.client_id =" . $search_result . ")";
   
    $result_client = mysqli_query($conn, $sql_client);
    $result_account = mysqli_query($conn, $sql_account);
    $result_receipts = mysqli_query($conn, $sql_receipts);
    
    $client = mysqli_fetch_assoc($result_client);
    $account = mysqli_fetch_assoc($result_account);
    $receipts = array();
    while($receipt_obj =  mysqli_fetch_assoc($result_receipts)) {
      array_push($receipts, $receipt_obj );
    }
    mysqli_close($conn);
    
    $client_name = ucfirst($client['last_name']) . ", " . ucfirst($client['first_name']);
    $account_n = $account['id'];
  ?>
  
  <h4> <?php echo $client_name ?> </h4>
  <h5> Account <?php echo $account_n ?> </h5>
  <form action="modules/actions/receipt.create.php" method="post" class="form-inline"> 
    <input type="hidden" class="hidden" name="receipt_create_msg">
    <div class="input-append">
      <input type="text" id="receipt_amount" name="amount" placeholder="Cantidad" required>
      <input type="submit" value="Pagar" class="btn">
    </div>
    <?php echo $msg ?>
    <table class='table'> 
      <thead>
        <tr>
          <?php
          foreach($receipts[0] as $key=>$value ) {
            echo "<th>" . $key . "</th>";
          }
          ?>
        </tr>
      </thead>
      <tbody>
        <?php
        foreach($receipts as $tmp_receipt) {
          echo "<tr>";
          foreach ($tmp_receipt as $key=>$value) {
            echo "<td>" . $value . "</td>";
          }
          echo "</tr>";
        }
        ?>
      </tbody>
    </table>
  </form>
</div>
